version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos
    network_mode: host
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs:/home/nacos/logs

  redis:
    image: redis:7.4.4
    container_name: redis
    network_mode: host
    command: redis-server --requirepass redis
    volumes:
      - ./redis/data:/data

  mysql:
    image: mysql:8.4.5
    container_name: mysql
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - ./mysql/data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq

  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    network_mode: host
    volumes:
      - ./nexus-data:/nexus-data